#!/bin/sh

# example slurm script intended for use in the WindHPC windpark

#SBATCH --time=4:00:00
#SBATCH -n 48

# code for energy measurement
t_start=$(date +%s)

# user code

module load mpi/openmpi/5.0.7-gcc-14.2.0

mpirun -n 48 --bind-to l3cache hostname

sleep 120


# code for energy measurement
t_end=$(date +%s)
echo "Start: $t_start End: $t_end"
python3 ./energy-reporter.py --start $t_start --end $t_end n000001 n000101 n000201 n000301 n000401 > run


